### ISSUE TITLE
why does this happen

### ISSUE THREAD

**Issue by wallcalldoll** [Walksy/ShieldStatus#2]
![image](https://github.com/user-attachments/assets/97b20461-baf5-4188-a9bf-ad0f67cfa05b)

**Comment by Whylord2** [comment]
yeah i got this problem too, y does this happen? is this a universal glitch for mod menu? It might be.

**Comment by Walksy** [comment]
This is a problem with lunar and YetAnotherConfigLib. If you want to change the values yourself, while using lunar, you'll have to change them manually in the config.

**Comment by itzCeso** [comment]
I am having the same issue. how do I access the config? I cant find it anywhere in the folders

**Comment by itzCeso** [comment]
> I am having the same issue. how do I access the config? I cant find it anywhere in the folders

Well I found the config folder but theres no shield status file inside
